DROP TABLE IF EXISTS AUTHORS; -- IF EXISTS

CREATE TABLE AUTHORS(
ID TEXT PRIMARY KEY,
NAME TEXT,
EASTERN_ORDER BOOLEAN,
PERSONAL_NAME TEXT,
ENUMERATION TEXT,
TITLE TEXT,
-- alternate_names[]
--uris[]
-- bio
LOCATION TEXT,
BIRTH_DATE TEXT,
DEATH_DATE TEXT,
DATE TEXT,
WIKIPEDIA TEXT);
--links