DROP TABLE IF EXISTS EDITION;

CREATE TABLE EDITION(
id text PRIMARY KEY,
title text,
title_prefix text,
subtitle text,
-- other_titles[] text,
-- authors[] text,
by_statement text,
publish_date text,
copyright_date text,
edition_name text,
-- languages[] text,
-- description text, # INSUPPORTER
-- notes text, # INSUPPORTER
-- genres[] text,
-- table_of_contents[] text,
-- work_titles[] text,
-- series[] text,
physical_dimensions text,
physical_format text,
number_of_pages integer,
-- subjects[] text,
pagination text,
-- lccn[] text,
ocaid text,
-- oclc_numbers[] text,
-- isbn_10[] text,
-- isbn_13[],
-- dewey_decimal_class[] text,
-- lc_classifications[] text,
-- contributions[] text,
-- publish_places[] text,
publish_country  text,
-- publishers[] text,
-- distributors[] text,
first_sentence text,
weight text,
-- location[] text,
scan_on_demand  boolean,
-- collections[] text // collection,
-- uris[] text,
-- uri_descriptions[] text,
translation_of  text,
-- works[] text // work,
-- source_records[] text,
-- translated_from[] text // language,
-- scan_records[] text // scan record,
-- volumes[] text // volume,
accompanying_material text)
